name: mollydouglas
favicon: null
layout_spectrum: 0.8819964190479368
typography_spectrum: 0.64801
title: Molly Douglas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.875
  lightness: 0.9557172984350473
  saturation: 0.8050855351611972
  rhythmicContrast: 0.25
purpose: []
